[tsl] ERROR in ./src/main.ts(84,18)       TS2531: Object is possibly 'null'.
[tsl] ERROR in ./src/main.ts(84,50)
      TS2339: Property 'value' does not exist on type 'HTMLElement'.

[tsl] ERROR in ./src/main.ts(105,5)
      TS2531: Object is possibly 'null'.

[tsl] ERROR in ./src/main.ts(105,40)
      TS2339: Property 'value' does not exist on type 'HTMLElement'.